name: CI/CD

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.DOCKER_REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: |
            ${{ secrets.DOCKER_REGISTRY }}/fountain-finder:latest
            ${{ secrets.DOCKER_REGISTRY }}/fountain-finder:${{ github.sha }}
          build-args: |
            GIT_SHA=${{ github.sha }}

      - name: Image digest
        if: ${{ steps.changelog.outputs.skipped == 'false' }}
        run: echo ${{ steps.docker_build.outputs.digest }}
