name: CI/CD

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: yarn install --immutable --immutable-cache
      - run: yarn build
        env:
          VITE_MAP_STYLE_KEY: ${{ secrets.VITE_MAP_STYLE_KEY }}

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: "^1.18"
      - name: Build go
        run: make build

      - name: rsync
        uses: burnett01/rsync-deployments@5.2
        with:
          switches: -avzr --delete
          path: build/
          remote_path: /apps/fountain-finder/
          remote_host: ${{ secrets.HOST }}
          remote_port: ${{ secrets.PORT }}
          remote_user: ${{ secrets.USER }}
          remote_key: ${{ secrets.KEY }}

      - name: Restart service
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            sudo /usr/bin/systemctl restart fountain-finder.service

